layout_spectrum: 0.5418904
color:
  saturation: 0.9683136
  brandStrength: 0.7663802
  lightness: 0.08216969
  brandColors:
    - '#FFFFFF'
    - '#CFBDA3'
    - '#5C4C39'
    - '#92887F'
    - '#C56539'
  rhythmicContrast: 0.5064447
typography_spectrum: 0.9113855
name: Tivy66
